import type { VisitorFormData } from "@/lib/types";

export type VisitorPreset = Omit<VisitorFormData, "session_uuid">;

/** Sample visitor records offered after a scan; session_uuid comes from the QR code. */
export const VISITOR_PRESETS: VisitorPreset[] = [
  {
    name: "Ahmed Raza",
    email: "ahmed.raza@ahtml.com.pk",
    phone: "+923211234567",
    visitortype: "CUSTOMER",
    is_existing: false,
    company_name: "Ahmad Hassan Textile Mills Limited",
    website: "https://www.ahtml.com.pk",
  },
  {
    name: "Sana Tariq",
    email: "sana.tariq@aatml.com.pk",
    phone: "+923001112233",
    visitortype: "CUSTOMER",
    is_existing: false,
    company_name: "Ali Asghar Textile Mills Limited",
    website: "https://www.aatml.com.pk",
  },
  {
    name: "Usman Ghani",
    email: "usman.ghani@allawasaya.com",
    phone: "+923454567890",
    visitortype: "CUSTOMER",
    is_existing: false,
    company_name: "Allawasaya Textile & Finishing Mills Limited",
    website: "https://www.allawasaya.com",
  },
  {
    name: "Fatima Noor",
    email: "fatima.noor@antextile.com.pk",
    phone: "+923335556677",
    visitortype: "CUSTOMER",
    is_existing: false,
    company_name: "AN Textile Mills Limited",
    website: "https://www.antextile.com.pk",
  },
  {
    name: "Imran Ali",
    email: "imran.ali@apollotextile.com",
    phone: "+923216667788",
    visitortype: "CUSTOMER",
    is_existing: false,
    company_name: "Apollo Textile Mills Limited",
    website: "https://www.apollotextile.com",
  },
  {
    name: "Zara Sheikh",
    email: "zara.sheikh@arctictextile.com",
    phone: "+923425678901",
    visitortype: "CUSTOMER",
    is_existing: false,
    company_name: "Arctic Textile Mills Limited",
    website: "https://www.arctictextile.com",
  },
  {
    name: "Hassan Mahmood",
    email: "hassan.mahmood@ashfaqtextile.com",
    phone: "+923308889900",
    visitortype: "CUSTOMER",
    is_existing: false,
    company_name: "Ashfaq Textile Mills Limited",
    website: "https://www.ashfaqtextile.com",
  },
  {
    name: "Ayesha Khan",
    email: "ayesha.khan@asimtextile.com",
    phone: "+923211223344",
    visitortype: "CUSTOMER",
    is_existing: false,
    company_name: "Asim Textile Mills Limited",
    website: "https://www.asimtextile.com",
  },
  {
    name: "Bilal Ahmed",
    email: "bilal.ahmed@umergroup.com",
    phone: "+923124567890",
    visitortype: "CUSTOMER",
    is_existing: false,
    company_name: "Bhanero Textile Mills Limited",
    website: "https://www.umergroup.com",
  },
  {
    name: "Saima Akhtar",
    email: "saima.akhtar@colonytextiles.com",
    phone: "+923001234567",
    visitortype: "CUSTOMER",
    is_existing: false,
    company_name: "Colony Textile Mills Limited",
    website: "https://www.colonytextiles.com",
  },
  {
    name: "Kamran Javed",
    email: "kamran.javed@aghasteel.com",
    phone: "+923334455667",
    visitortype: "CUSTOMER",
    is_existing: false,
    company_name: "Agha Steel Industries Limited",
    website: "https://www.aghasteel.com",
  },
  {
    name: "Nadia Ali",
    email: "nadia.ali@agriauto.com.pk",
    phone: "+923124567891",
    visitortype: "CUSTOMER",
    is_existing: false,
    company_name: "Agriauto Industries Limited",
    website: "https://www.agriauto.com.pk",
  },
  {
    name: "Farhan Anwar",
    email: "farhan.anwar@aruj.com",
    phone: "+923215678902",
    visitortype: "CUSTOMER",
    is_existing: false,
    company_name: "Aruj Industries Limited",
    website: "https://www.aruj.com",
  },
  {
    name: "Hina Tariq",
    email: "hina.tariq@biafo.com",
    phone: "+923416789012",
    visitortype: "CUSTOMER",
    is_existing: false,
    company_name: "Biafo Industries Limited",
    website: "https://www.biafo.com",
  },
  {
    name: "Muhammad Ilyas",
    email: "muhammad.ilyas@biic.com.pk",
    phone: "+923009988776",
    visitortype: "CUSTOMER",
    is_existing: false,
    company_name: "Business & Industrial Insurance Company Ltd.",
    website: "https://www.biic.com.pk",
  },
  {
    name: "Rubina Shaheen",
    email: "rubina.shaheen@dsil.com.pk",
    phone: "+923331112222",
    visitortype: "CUSTOMER",
    is_existing: false,
    company_name: "D.S. Industries Limited",
    website: "https://www.dsil.com.pk",
  },
  {
    name: "Shahid Afridi",
    email: "shahid.afridi@mhdadabhoy.com",
    phone: "+923224455667",
    visitortype: "CUSTOMER",
    is_existing: false,
    company_name: "Dadabhoy Cement Industries Limited",
    website: "https://www.mhdadabhoy.com",
  },
  {
    name: "Amina Asif",
    email: "amina.asif@diamondfoam.com",
    phone: "+923455678901",
    visitortype: "CUSTOMER",
    is_existing: false,
    company_name: "Diamond Industries Limited",
    website: "https://www.diamondfoam.com",
  },
  {
    name: "Naveed Ahmed",
    email: "naveed.ahmed@roadprince.com.pk",
    phone: "+923098765432",
    visitortype: "CUSTOMER",
    is_existing: false,
    company_name: "Eiffel Industries Limited",
    website: "https://www.roadprince.com.pk",
  },
  {
    name: "Sadia Malik",
    email: "sadia.malik@emco.com.pk",
    phone: "+923456789012",
    visitortype: "CUSTOMER",
    is_existing: false,
    company_name: "Emco Industries Limited",
    website: "https://www.emco.com.pk",
  },
];
